- name : Configure Docker on EC2 Instances
  hosts : all
  become: true
  connection : ssh
  tasks : 
  - name: updating apt
    command : sudo apt-get update

  - name : Install Docker
    command : sudo apt-get install -y docker.io

  - name : Start Docker Service
    command : sudo systemctl start docker

    - name: Log in to private Docker registry
      docker_login:
        registry: "{{ https://hub.docker.com/ }}"
        username: "{{ vedanshsri }}"
        password: "{{ dckr_pat_oOJp6ha0BOxnyzJbQRqLvh0Fboc }}"
      register: login_result
      no_log: true  # Prevents password from being logged

    - name: Pull image from private registry
      docker_image:
        name: "{{ vedanshsri/myimg6 }}"
        source: pull
        state: present
        force_source: yes  # Forces pull even if image exists
      register: pull_result

    - name: Deploy Docker Container
      command: docker run -dt -p 8091:8091 --name c000 vedanshsri/myimg2
